version: "3"
services:
  
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: gujarat
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"
    ports:
      - 3306

  php:
    build: .
    container_name: php
    ports:
      - 80:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - 8081:80
    depends_on:
      - mysql