version: "3"

services:
  mysql:
    image: mysql
    container_name: mysql
    networks:
      - my-network
  php:
    image: php
    container_name: php
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
